apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
  spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
	storageClassName: standard-rwo
---
apiVersion: app/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
  spec:
    selector:
        matchlabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
            - image: Pmacoy/k8s-projeto1-app-base
              args: 
              - "--ignore-db-dir=lost+found"
              imagePullPolicy: Always
              - name: mysql
              ports:
              - containerPort: 3306
                name: mysql  

              volumeMounts:    
              - name: mysql-dados
                mountPath: /var/lib/mysql/
        volumes:
            - name: mysql-dados
              persistentVolumeClaim:
                claimName: mysql-dados
				
---
piVersion: app/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
  spec:
	replicas: 6
	selector: 
		matchlabels: 
			app: php
	template:
		metadata:
			labels:
				app: php
	spec:
		containers:
		- name: php
		  image: Pmacoy/k8s-projeto1-app-base
		  imagePullPolicy: Always
		  ports:
		  - containerPort: 80